---
title: Roland Lazarte
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Portfolio of cinematographer Roland Lazarte
baseurl: 
url: http://rolandlazarte.com
markdown: kramdown
