---
title: Roland Lazarte
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Portfolio of Roland Lazarte
baseurl: 
url: http://anin.ag
markdown: kramdown
