---
title: Roland Lazarte
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: {}
description: |
  {{site.description}}.
baseurl: ''
url: http://anin.ag
twitter_username: {}
github_username: {}
markdown: kramdown
